version: '3.1'
services:
  app:
    container_name: "app"
    image: "disaster-response"
    build: ../../..
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
        - SPRING_DATASOURCE_USERNAME=${PROD_DB_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${PROD_DB_PASSWORD}
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PROD_DB_USERNAME}
      - POSTGRES_PASSWORD=${PROD_DB_PASSWORD}

